# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1303, 858)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 80, 751, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linewithadress = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linewithadress.sizePolicy().hasHeightForWidth())
        self.linewithadress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.linewithadress.setFont(font)
        self.linewithadress.setText("")
        self.linewithadress.setObjectName("linewithadress")
        self.horizontalLayout.addWidget(self.linewithadress)
        self.find = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.find.setObjectName("find")
        self.horizontalLayout.addWidget(self.find)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 290, 751, 439))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.discription = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.discription.setFont(font)
        self.discription.setObjectName("discription")
        self.gridLayout.addWidget(self.discription, 1, 0, 1, 2)
        self.TextTemp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TextTemp.setObjectName("TextTemp")
        self.gridLayout.addWidget(self.TextTemp, 2, 0, 1, 1)
        self.humidity = QtWidgets.QLabel(self.gridLayoutWidget)
        self.humidity.setObjectName("humidity")
        self.gridLayout.addWidget(self.humidity, 4, 1, 1, 1)
        self.TextPressure = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TextPressure.setObjectName("TextPressure")
        self.gridLayout.addWidget(self.TextPressure, 3, 0, 1, 1)
        self.temp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp.setObjectName("temp")
        self.gridLayout.addWidget(self.temp, 2, 1, 1, 1)
        self.pressure = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pressure.setObjectName("pressure")
        self.gridLayout.addWidget(self.pressure, 3, 1, 1, 1)
        self.texthumidity = QtWidgets.QLabel(self.gridLayoutWidget)
        self.texthumidity.setObjectName("texthumidity")
        self.gridLayout.addWidget(self.texthumidity, 4, 0, 1, 1)
        self.TextCurrentWeather = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TextCurrentWeather.setObjectName("TextCurrentWeather")
        self.gridLayout.addWidget(self.TextCurrentWeather, 0, 0, 1, 2)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(630, 150, 251, 141))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.temp_9h = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.temp_9h.setObjectName("temp_9h")
        self.gridLayout_4.addWidget(self.temp_9h, 2, 0, 1, 1)
        self.pres_9h = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.pres_9h.setObjectName("pres_9h")
        self.gridLayout_4.addWidget(self.pres_9h, 2, 1, 1, 1)
        self.h9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.h9.setObjectName("h9")
        self.gridLayout_4.addWidget(self.h9, 0, 0, 1, 2)
        self.discr_9h = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.discr_9h.setObjectName("discr_9h")
        self.gridLayout_4.addWidget(self.discr_9h, 1, 0, 1, 2)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(380, 150, 251, 141))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.discr_6h = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.discr_6h.setObjectName("discr_6h")
        self.gridLayout_5.addWidget(self.discr_6h, 1, 0, 1, 2)
        self.pres_6h = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.pres_6h.setObjectName("pres_6h")
        self.gridLayout_5.addWidget(self.pres_6h, 2, 1, 1, 1)
        self.h6 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.h6.setObjectName("h6")
        self.gridLayout_5.addWidget(self.h6, 0, 0, 1, 2)
        self.temp_6h = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.temp_6h.setObjectName("temp_6h")
        self.gridLayout_5.addWidget(self.temp_6h, 2, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(130, 150, 251, 141))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.temp_3h = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.temp_3h.setObjectName("temp_3h")
        self.gridLayout_6.addWidget(self.temp_3h, 2, 0, 1, 1)
        self.pres_3h = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.pres_3h.setObjectName("pres_3h")
        self.gridLayout_6.addWidget(self.pres_3h, 2, 1, 1, 1)
        self.h3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.h3.setObjectName("h3")
        self.gridLayout_6.addWidget(self.h3, 0, 0, 1, 2)
        self.discr_3h = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.discr_3h.setObjectName("discr_3h")
        self.gridLayout_6.addWidget(self.discr_3h, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1303, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuWeather_Forecast = QtWidgets.QMenu(self.menubar)
        self.menuWeather_Forecast.setObjectName("menuWeather_Forecast")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWeather_Forecast.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Enter the place (Street, Сity)"))
        self.discription.setText(_translate("MainWindow", "TextLabel"))
        self.TextTemp.setText(_translate("MainWindow", "Temperature, C"))
        self.humidity.setText(_translate("MainWindow", "TextLabel"))
        self.TextPressure.setText(_translate("MainWindow", "Pressure, mm Hg"))
        self.temp.setText(_translate("MainWindow", "TextLabel"))
        self.pressure.setText(_translate("MainWindow", "TextLabel"))
        self.texthumidity.setText(_translate("MainWindow", "Humidity, %"))
        self.TextCurrentWeather.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Current Weather</span></p></body></html>"))
        self.temp_9h.setText(_translate("MainWindow", "TextLabel"))
        self.pres_9h.setText(_translate("MainWindow", "TextLabel"))
        self.h9.setText(_translate("MainWindow", "TextLabel"))
        self.discr_9h.setText(_translate("MainWindow", "TextLabel"))
        self.discr_6h.setText(_translate("MainWindow", "TextLabel"))
        self.pres_6h.setText(_translate("MainWindow", "TextLabel"))
        self.h6.setText(_translate("MainWindow", "TextLabel"))
        self.temp_6h.setText(_translate("MainWindow", "TextLabel"))
        self.temp_3h.setText(_translate("MainWindow", "TextLabel"))
        self.pres_3h.setText(_translate("MainWindow", "TextLabel"))
        self.h3.setText(_translate("MainWindow", "TextLabel"))
        self.discr_3h.setText(_translate("MainWindow", "TextLabel"))
        self.menuWeather_Forecast.setTitle(_translate("MainWindow", "Weather Forecast"))

